services:
  pg:
    image: postgres:15-alpine
    restart: always
    ports:
      - '${DATABASE_PORT}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pd_data:/var/lib/postgres/data

volumes:
  pd_data:
